<a href="https://colab.research.google.com/github/bohyuncho/ds-admission-challenge/blob/master/bohyun_of_ds_bootcamp_admission_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge

- 코드스테이츠 DS 부트캠프 어드미션을 위한 Challenge 과제 입니다. 
- 아래 challenge 를 풀기 위해 제공된 강의가 모든 것을 알려주진 않습니다. 
- 따라서 필요한 부분은 스스로 google 검색을 통해 이 challenge 를 완성해 주셔야 합니다. 
- 각 shell 에 필요한 부분을 작성하신 후 함께 링크를 제출해 주시면 됩니다.
- 모든 결과물은 하나의 shell에서 모두 실행될 수 있도록 print문을 사용해 주세요. run all 했을 때 전체 shell 이 모두 잘 실행될 수 있도록 관리해 주세요.



In [ ]:
# 원래 냈던 답안
# 1. 다음의 list 에서 두 번째 list elemnet 를 print 해 보세요
list_01 = ['Paul', 'John', 'Ringo', 'George']
print(list_01[1])

John


In [ ]:
# 새로 공부를 위한 답안
# 1. 다음의 list 에서 두 번째 list elemnet 를 print 해 보세요
list_01 = ['Paul', 'John', 'Ringo', 'George']
# python은 0부터 시작된다.
print(list_01[0]) 
print(list_01[1]) 
print(list_01[2]) 
print(list_01[3]) 

Paul
John
Ringo
George


In [ ]:
# 원래 냈던 답안
# 2. 다음의 list in the list에서 두 번째 element 를 print 해 보세요
list_02 = [['Paul', 'John', 'Ringo', 'George']]
print(list_02[0][1])

John


In [ ]:
# 새로 공부를 위한 답안
# 2. 다음의 list in the list에서 두 번째 element 를 print 해 보세요
list_02 = [['Paul', 'John', 'Ringo', 'George'],[1, 2, 3, 4]]
print(list_02[0][0])
print(list_02[1][1])
print(list_02[3][2]) # 없는 것은 프린트 되지 않고 에러코드 발생됨


Paul
2


IndexError: ignored

In [ ]:
# 원래 냈던 답안
# Initializing list  
list_01 = [ 1, 6, 3, 5, 3, 4 ] 
list_02 = [ 1, 6, 3, 5, 3] 

# 3.for loop을 이용하여 두 개의 리스트 안에 4가 있는지 없는지 print 하는 코드를 작성하세요

list_03 = []
list_03.extend(list_01)
list_03.extend(list_02)

#print(list_03)

number = 0

for list in list_03:
  number = number + 1

  if list == 4 and len(list_01) >= number:
    print("list_01 %d번에 있습니다" % number)
  
  elif list == 4 and len(list_01) < number:
    print("list_02 %d번에 있습니다" % (number-len(list_01)))

list_01 6번에 있습니다


In [ ]:
# 새로 공부를 위한 답안
# 3.for loop을 이용하여 두 개의 리스트 안에 4가 있는지 없는지 print 하는 코드를 작성하세요

list_01 = [ 1, 6, 3, 5, 3, 4 ] 
# 원래는 카운트를 돌리며 숫자를 세는 구조
count = 0 #임시로 설정한 숫자세는 값, 다른 단어로 변경해도 됨
for i in list_01 :
  # if list_01[i] == 4, range() >> 하는 다른 코딩도 있음
  if i == 4 : count = 1
  # if list_01에 4가 있음 : = 1로 설정
  # 없으면 count = 0

if(count == 1) : print("여기 list_01에 4가 있어요")
else : print("여기 list_01에 4가 없어요")

# 동일하게 한번 더, 변수값만 변경하고 진행
list_02 = [ 1, 6, 3, 5, 3] 

count = 0 
for i in list_02 :
  if i == 4 : count = 1

if(count == 1) : print("여기 list_02에 4가 있어요")
else : print("여기 list_02에 4가 없어요")


여기 list_01에 4가 있어요
여기 list_02에 4가 없어요


In [ ]:
# 원래 냈던 답안
# 4. 위 코드 역할을 하는 함수를 작성해 보세요
list_01 = [ 1, 6, 3, 4 ] 
list_02 = [ 1, 6, 4, 3 ] 

def countCheck(list_01, list_02):
  returnValue = 0
  number = 0
  
  list_03 = []
  list_03.extend(list_01)
  list_03.extend(list_02)

  for list in list_03:
    number = number + 1 

    if list == 4 and len(list_01) >= number:
      print("list_01 %d번에 있습니다" % number)
    elif list == 4 and len(list_01) < number:
      print("list_02 %d번에 있습니다" % (number-len(list_01)))

countCheck(list_01, list_02)

list_01 4번에 있습니다
list_02 3번에 있습니다


In [ ]:
# 새로 공부를 위한 답안
# 4. 위 코드 역할을 하는 함수를 작성해 보세요
list_05 = [ 1, 6, 3, 4 ] 
list_06 = [ 1, 6, 4, 3 ] 

def DSFT(L):
  count = 0
  for i in L :
    if i == 4 : count = 1
  if(count == 1) : print("여기 4가 있어요")
  else : print('없어요')

  DSFT(list_05)
  DSFT(list_06)


In [ ]:
# 원래 냈던 답안
list_04 = [4, 5, 8, 9, 10] 
# 5.위 list element 중 8보다 큰 숫자가 몇 개가 있는지 코드로 작성해 보세요. 

x = [i for i in list_04 if i >8]
#value of x
len(x)

#or 

#def length_of list(list_of_number, number):
#  x = [i for i in list_of_number if list_04 > number]
#  return len(x)
#length_of_list(list_04,8)


2

In [ ]:
# 새로 공부를 위한 답안
list_04 = [4, 5, 8, 9, 10] 
# 5.위 list element 중 8보다 큰 숫자가 몇 개가 있는지 코드로 작성해 보세요. 

def length_of list(list_of_number, number):
  x = [i for i in list_of_number if list_04 > number]
  return len(x)
length_of_list(list_04,8)




SyntaxError: ignored

In [ ]:
# 원래 냈던 답안
# 6. BMI
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

#print(type(height))
# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

# bmi = weight / height ** 2 를 numpy array 활용하여 구해보세요

bmi = np_weight / np_height ** 2

# bmi 가 24 이상인 값들만 선택해 보세요

cond = bmi >= 24
bmi[cond]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

In [2]:
# 새로 공부를 위한 답안
# 6.BMI
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# bmi = weight / height ** 2 를 numpy array 활용하여 구해보세요
# bmi 가 24 이상인 값들만 선택해 보세요

import numpy as np
h = np.array(height)
w = np.array(weight)

print(h)

bmi = w / h ** 2

print(bmi)

idx = np.where(bmi>24)
print(bmi[idx])


[1.87 1.87 1.82 1.91 1.9  1.85]
[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
[27.88755755 28.75558507 25.48723993 25.84368152]


In [ ]:
# 원래 냈던 답안
# 7. pandas 패키지 라이브러리를 불러오세요

# 아래 내용을 담는 pandas Dataframe 을 생성하세요
# {'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}

dict = {"Bob":['I liked it.', 'It was awful.'],"Sue":['Pretty good.', 'Bland.']}
import pandas as pd
brics = pd.DataFrame(dict)
print(brics)


             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.


In [ ]:
# 새로 공부를 위한 답안
# 7. pandas 패키지 라이브러리를 불러오세요
data = {"Bob":['I liked it.', 'It was awful.'],"Sue":['Pretty good.', 'Bland.']}
pd.DataFrame(data, index = ['A', 'B'])

Bob           Sue
A    I liked it.  Pretty good.
B  It was awful.        Bland.

In [ ]:
# 원래 냈던 답안
# 8. 아래와 같은 dataframe을 만들어 보세요. (참고: 연도가 index가 되게 해 주세요)
"""
year dept     revenue
2015 Sales    30
2016 Sales    35
2017 Sales    40
"""
dict = {"year":['2015','2016','2017'],"dept":['Sales','Sales','Sales',],"revenue":['30','35','40']}

import pandas as pd
brics = pd.DataFrame(dict)

brics = brics.set_index("year")

print(brics)

# 2017년 데이터만 선택해 보세요

#brics.iloc[2]

print(brics.loc['2017',:])

# 조건(condition)을 활용하여 revenue 30 이상으로만 filter 해 보세요. reference: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/03_subset_data.html 

brics[brics.revenue >='30'].head()


       dept revenue
year               
2015  Sales      30
2016  Sales      35
2017  Sales      40
dept       Sales
revenue       40
Name: 2017, dtype: object


dept revenue
year               
2015  Sales      30
2016  Sales      35
2017  Sales      40

In [ ]:
# 새로 공부를 위한 답안
# 8. 아래와 같은 dataframe을 만들어 보세요. (참고: 연도가 index가 되게 해 주세요)

In [ ]:
# 원래 냈던 답안
# 9.'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv' 자료를 불러와 dataframe으로 만들어 보세요 
import pandas as pd
df1 = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
df1.head()

Survived  Pclass  ... Parents/Children Aboard     Fare
0         0       3  ...                       0   7.2500
1         1       1  ...                       0  71.2833
2         1       3  ...                       0   7.9250
3         1       1  ...                       0  53.1000
4         0       3  ...                       0   8.0500

[5 rows x 8 columns]

In [ ]:
# 새로 공부를 위한 답안
# 9.'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv' 자료를 불러와 dataframe으로 만들어 보세요 
import pandas as pd
titanic = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
titanic.head()


Survived  Pclass  ... Parents/Children Aboard     Fare
0         0       3  ...                       0   7.2500
1         1       1  ...                       0  71.2833
2         1       3  ...                       0   7.9250
3         1       1  ...                       0  53.1000
4         0       3  ...                       0   8.0500

[5 rows x 8 columns]

In [ ]:
# 원래 냈던 답안
# 10.
# 타이타닉 데이터의 shape은 어떻게 되나요?  > (887, 8)
print(df1.shape)

# 타이타닉 row record에서 10~20번째 줄을 출력해 보세요
print(df1[9:20])

# 타이타닉 데이터에서 'Survived', 'Age', 'Sex' 칼럼 데이터를 선택해 보세요
print(df1[['Survived','Age', 'Sex']])

# 타이타닉 데이터에서 생존자 데이터만 골라보세요 > 342 생존
print(df1[df1['Survived'].isin(['1'])])

# 생존자 데이터 중 여자, 남자 중 누가 더 많나요? >> 109 남자/233 여자로 여자가 더 많습니다 참고: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html

#print(df[df['Survived'].isin(['1','female'])].value_counts())
#df = df[df['Survived'].isin(['1'])]
#print(df[df['Sex'].isin(['male'])].value_counts())

#df[['Sex', 'Survived']].groupby(['Sex'], as_index=False).mean().sort_values(by='Survived', ascending=False)

pin = df1[df1['Survived'].isin(['1'])]
maleCnt = len(pin[pin['Sex'].isin(['male'])])
femaleCnt = len(pin[pin['Sex'].isin(['female'])])

if maleCnt > femaleCnt:
    print("남자가 더 많습니다.")
elif maleCnt < femaleCnt:
    print("여자가 더 많습니다.")
else:
    print("여자와 남자가 같습니다.")


(887, 8)
    Survived  Pclass  ... Parents/Children Aboard     Fare
9          1       2  ...                       0  30.0708
10         1       3  ...                       1  16.7000
11         1       1  ...                       0  26.5500
12         0       3  ...                       0   8.0500
13         0       3  ...                       5  31.2750
14         0       3  ...                       0   7.8542
15         1       2  ...                       0  16.0000
16         0       3  ...                       1  29.1250
17         1       2  ...                       0  13.0000
18         0       3  ...                       0  18.0000
19         1       3  ...                       0   7.2250

[11 rows x 8 columns]
     Survived   Age     Sex
0           0  22.0    male
1           1  38.0  female
2           1  26.0  female
3           1  35.0  female
4           0  35.0    male
..        ...   ...     ...
882         0  27.0    male
883         1  19.0  female
884     

In [ ]:
# 새로 공부를 위한 답안
# 10.
# 타이타닉 데이터의 shape은 어떻게 되나요? 
print(titanic.shape) # dimension row / column

# 타이타닉 row record에서 10~20번째 줄을 출력해 보세요
print(titanic[10:21]) # 원래 처음시작이 0 부터 시작이지만, 실질적으로 옆에 숫자가 표시되는 기준으로 했을 때

# 타이타닉 데이터에서 'Survived', 'Age', 'Sex' 칼럼 데이터를 선택해 보세요
print(titanic[['Survived','Age', 'Sex']])

# 타이타닉 데이터에서 생존자 데이터만 골라보세요 

# 생존자 데이터 중 여자, 남자 중 누가 더 많나요? 참고: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html


(887, 8)
    Survived  Pclass  ... Parents/Children Aboard     Fare
10         1       3  ...                       1  16.7000
11         1       1  ...                       0  26.5500
12         0       3  ...                       0   8.0500
13         0       3  ...                       5  31.2750
14         0       3  ...                       0   7.8542
15         1       2  ...                       0  16.0000
16         0       3  ...                       1  29.1250
17         1       2  ...                       0  13.0000
18         0       3  ...                       0  18.0000
19         1       3  ...                       0   7.2250
20         0       2  ...                       0  26.0000

[11 rows x 8 columns]
     Survived   Age     Sex
0           0  22.0    male
1           1  38.0  female
2           1  26.0  female
3           1  35.0  female
4           0  35.0    male
..        ...   ...     ...
882         0  27.0    male
883         1  19.0  female
884     