<a href="https://colab.research.google.com/github/sekwangoh/ds-admission-challenge/blob/master/DAY4_admission_Challenge_(bootcamp_admission_challenge).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge

- 코드스테이츠 DS 부트캠프 어드미션을 위한 Challenge 과제 입니다. 
- 아래 challenge 를 풀기 위해 제공된 강의가 모든 것을 알려주진 않습니다. 
- 따라서 필요한 부분은 스스로 google 검색을 통해 이 challenge 를 완성해 주셔야 합니다. 
- 각 shell 에 필요한 부분을 작성하신 후 함께 링크를 제출해 주시면 됩니다.
- 모든 결과물은 하나의 shell에서 모두 실행될 수 있도록 print문을 사용해 주세요. run all 했을 때 전체 shell 이 모두 잘 실행될 수 있도록 관리해 주세요.



In [ ]:
# 1. 다음의 list 에서 두 번째 list elemnet 를 print 해 보세요
list_01 = ['Paul', 'John', 'Ringo', 'George']

list_01[1]

'John'

In [ ]:
# 2. 다음의 list in the list에서 두 번째 element 를 print 해 보세요
list_02 = [['Paul', 'John', 'Ringo', 'George']]

list_02[0][1]

'John'

In [165]:
# Initializing list  
list_01 = [ 1, 6, 3, 5, 3, 4 ] 
list_02 = [ 1, 6, 3, 5, 3 ] 
 
# for loop을 이용하여 두 개의 리스트 안에 4가 있는지 없는지 print 하는 코드를 작성하세요

count = 0 
for i in list_01:
  if i == 4:
    count += 1
    if count == 1:
      print("4가 있네요!")  
  else:
      count += 1
      if count == len(list_02)-1: 
        print("4가 없네요!")  

   

count = 0 
for i in list_02:
  if i == 4:
    count += 1
    if count == 1:
      print("4가 있네요!")  
  else:
    count += 1
    if count == len(list_02)-1: 
      print("4가 없네요!")  

      


4가 없네요!
4가 없네요!


In [169]:
# 위 코드 역할을 하는 함수를 작성해 보세요

"""
count1 = 0
count2 = 0

def list_number(x):
  for i in x:
    if i == 4:
      count1 += 1
      if count1 == 1:
        print("4가 있네요!")  
    else:       
      count2 += 1
      if count2 == len(x)-1: 
        print("4가 없네요!")  

list_number(list_01)
list_number(list_02) 
"""

def list_number(x):
  if 4 in x:
    print("4가 있네요!")
  else:
    print("4가 없네요!")



list_number(list_01)
list_number(list_02)
      
  



4가 있네요!
4가 없네요!


In [ ]:
*list_03 = [4, 5, 8, 9, 10] 
# 위 list element 중 8보다 큰 숫자가 몇 개가 있는지 코드로 작성해 보세요. 
count = 0
for i in list_03:
  if i > 8:
    count += 1
print("list element가 8보다 큰 수의 갯수는", count ,"이다.")

list element가 8보다 큰 수의 갯수는 2 이다.


In [ ]:
# BMI
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# print(np.version) 버전체크
import numpy as np

np_height = np.array([1.87,  1.87, 1.82, 1.91, 1.90, 1.85])
np_weight = np.array([81.65, 97.52, 95.25, 92.98, 86.18, 88.45])

print(np_height)
print(np_weight)

# bmi = weight / height ** 2 를 numpy array 활용하여 구해보세요

bmi = np_weight / np_height ** 2

print(bmi)

# bmi 가 24 이상인 값들만 선택해 보세요

## print(bmi >= 24) boolean으로 값을 나타낼 수 있다. 
print(bmi[bmi>=24])



[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]
[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
[False  True  True  True False  True]
[27.88755755 28.75558507 25.48723993 25.84368152]


In [ ]:
# pandas 패키지 라이브러리를 불러오세요
import pandas as pd

# 아래 내용을 담는 pandas Dataframe 을 생성하세요
df = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})
# {'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}

print(df)
## display(df)

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.


Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [ ]:
# 아래와 같은 dataframe을 만들어 보세요. (참고: 연도가 index가 되게 해 주세요)
"""
year dept     revenue
2015 Sales    30
2016 Sales    35
2017 Sales    40
"""

import pandas as pd
df = pd.DataFrame({'year' : [2015, 2016, 2017], 'dept' : ['Sales','Sales','Sales'], 'revenue' : [30,35,40]})
display(df)



# 2017년 데이터만 선택해 보세요
display(df[df['year']==2017])

#print(df[df['year']== 2017])

# 조건(condition)을 활용하여 revenue 30 이상으로만 filter 해 보세요. reference: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/03_subset_data.html 

display(df[df['revenue'] >= 30])



year   dept  revenue
0  2015  Sales       30
1  2016  Sales       35
2  2017  Sales       40

year   dept  revenue
2  2017  Sales       40

year   dept  revenue
0  2015  Sales       30
1  2016  Sales       35
2  2017  Sales       40

In [ ]:
# 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv' 자료를 불러와 dataframe으로 만들어 보세요 
df = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')

print(df)


     Survived  Pclass  ... Parents/Children Aboard     Fare
0           0       3  ...                       0   7.2500
1           1       1  ...                       0  71.2833
2           1       3  ...                       0   7.9250
3           1       1  ...                       0  53.1000
4           0       3  ...                       0   8.0500
..        ...     ...  ...                     ...      ...
882         0       2  ...                       0  13.0000
883         1       1  ...                       0  30.0000
884         0       3  ...                       2  23.4500
885         1       1  ...                       0  30.0000
886         0       3  ...                       0   7.7500

[887 rows x 8 columns]


In [175]:
# 타이타닉 데이터의 shape은 어떻게 되나요? 
display(df.shape)

# 타이타닉 row record에서 10~20번째 줄을 출력해 보세요
display(df.iloc[10:21])

# 타이타닉 데이터에서 'Survived', 'Age', 'Sex' 칼럼 데이터를 선택해 보세요
display(df[['Survived','Age', 'Sex']])

# 타이타닉 데이터에서 생존자 데이터만 골라보세요

display(df[df['Survived']== 1])

# 생존자 데이터 중 여자, 남자 중 누가 더 많나요? 참고: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html
Survived_number = df[df['Survived']== 1]

display(Survived_number['Sex'].value_counts())
"""
Survived_number[df['Sex'] == 'female'].value_counts()
Survived_number = df[df['Survived']== 1]['Sex'].value_counts()
Survived_sex = Survived_number['Sex']
Survived_sex['female']
"""

(887, 8)

Survived  Pclass  ... Parents/Children Aboard     Fare
10         1       3  ...                       1  16.7000
11         1       1  ...                       0  26.5500
12         0       3  ...                       0   8.0500
13         0       3  ...                       5  31.2750
14         0       3  ...                       0   7.8542
15         1       2  ...                       0  16.0000
16         0       3  ...                       1  29.1250
17         1       2  ...                       0  13.0000
18         0       3  ...                       0  18.0000
19         1       3  ...                       0   7.2250
20         0       2  ...                       0  26.0000

[11 rows x 8 columns]

Survived   Age     Sex
0           0  22.0    male
1           1  38.0  female
2           1  26.0  female
3           1  35.0  female
4           0  35.0    male
..        ...   ...     ...
882         0  27.0    male
883         1  19.0  female
884         0   7.0  female
885         1  26.0    male
886         0  32.0    male

[887 rows x 3 columns]

Survived  Pclass  ... Parents/Children Aboard     Fare
1           1       1  ...                       0  71.2833
2           1       3  ...                       0   7.9250
3           1       1  ...                       0  53.1000
8           1       3  ...                       2  11.1333
9           1       2  ...                       0  30.0708
..        ...     ...  ...                     ...      ...
871         1       3  ...                       0   7.2250
875         1       1  ...                       1  83.1583
876         1       2  ...                       1  26.0000
883         1       1  ...                       0  30.0000
885         1       1  ...                       0  30.0000

[342 rows x 8 columns]

female    233
male      109
Name: Sex, dtype: int64

"\nSurvived_number[df['Sex'] == 'female'].value_counts()\nSurvived_number = df[df['Survived']== 1]['Sex'].value_counts()\nSurvived_sex = Survived_number['Sex']\nSurvived_sex['female']\n"