<a href="https://colab.research.google.com/github/mynameisji/ds-admission-challenge/blob/master/ds_bootcamp_admission_%EC%86%A1%EC%A7%80_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge

- 코드스테이츠 DS 부트캠프 어드미션을 위한 Challenge 과제 입니다. 
- 아래 challenge 를 풀기 위해 제공된 강의가 모든 것을 알려주진 않습니다. 
- 따라서 필요한 부분은 스스로 google 검색을 통해 이 challenge 를 완성해 주셔야 합니다. 
- 각 shell 에 필요한 부분을 작성하신 후 함께 링크를 제출해 주시면 됩니다.
- 모든 결과물은 하나의 shell에서 모두 실행될 수 있도록 print문을 사용해 주세요. run all 했을 때 전체 shell 이 모두 잘 실행될 수 있도록 관리해 주세요.



In [9]:
# 1. 다음의 list 에서 두 번째 list elemnet 를 print 해 보세요
list_01 = ['Paul', 'John', 'Ringo', 'George']

print(list_01[1])

#이렇게 [] 형태의 자료를 list 자료형이라고 한다. Array(배열)과 비슷한데, 여러 다른 종류의 변수를 저장하고 싶은 만큼 저장할 수 있다.
#list_01[1] -> list_01의 두번째 요소값을 말한다. Python은 숫자를 0부터 센다. 

John


In [7]:
# 2. 다음의 list in the list에서 두 번째 element 를 print 해 보세요
list_02 = [['Paul', 'John', 'Ringo', 'George']]

#list안에 list가 들어가는 건 물론, list안에 요소와 다른 list가 동시에 들어 갈 수도 있다. ex) list_a = [1, 2, 3, [4, 5]]
#list_02의 첫번째 요소가 ['Paul', 'John', 'Ringo', 'George']이고, 이 첫번째 요소 중 두번째 요소는 'John'이다.

print(list_02[0][1])

#혹은 보기 편하게 list in the list를 a라는 변수로 설정해보자.
 
a = ['Paul', 'John', 'Ringo', 'George'] 
print(a[1])


John
John


In [61]:
# Initializing list  
list_01 = [ 1, 6, 3, 5, 3, 4 ] 
list_02 = [ 1, 6, 3, 5, 3 ] 
 
# for loop을 이용하여 두 개의 리스트 안에 4가 있는지 없는지 print 하는 코드를 작성하세요


for i in list_01:
  if 4 in list_01:
    print("There's 4 in list_01")
    break
  else:
    print("There isn't 4 in list_01")
    break

for i in list_02:
  if 4 in list_02:
    print("There's 4 in list_02")
  else:
    print("There isn't 4 in list_02")
    break


#for문을 사용하는 반복문에서 break를 사용하면 반복문 전체를 빠져나오게 된다.
#만약 break가 없다면 4 가 아닌 요소 각각에 출력물이 나온다. 


There's 4 in list_01
There isn't 4 in list_02


In [70]:
# 위 코드 역할을 하는 함수를 작성해 보세요

def numbers(L):
  count = 0
  for i in L:
    if i == 4 : count = 1
  if(count == 1) : print("There's 4 in here")
  else: print("There isn't 4 in here")
 
numbers(list_01)
numbers(list_02)


There's 4 in here
There isn't 4 in here


In [71]:
list_03 = [4, 5, 8, 9, 10] 
# 위 list element 중 8보다 큰 숫자가 몇 개가 있는지 코드로 작성해 보세요. 

sum(i > 8 for i in list_03)

#코드가 도저히 안 풀리면 잘 검색해서 누군가 만들어 놓은걸 찾는 것도 방법이라고 했다..

2

In [74]:
# BMI
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# bmi = weight / height ** 2 를 numpy array 활용하여 구해보세요
import numpy as np
height = np.array(height)
weight = np.array(weight)

bmi = weight / height ** 2
print(bmi)

#numpy는 리스트를 배열로 변환해주는 파이썬 패키지다. 배열을 사용하면 적은 메모리로 데이터를 빠르게 처리할 수 있다.
#numpy의 array라는 함수에 리스트(여기서는 height와 weight)를 넣어주면 배열로 변환해준다.
#이렇게 .~ 이 함수를 사용한다는 의민줄 처음 알았다...

# bmi 가 24 이상인 값들만 선택해 보세요
cond = bmi > 24
print(bmi[cond])

#bmi>24의 조건을 cond라는 변수에 정의하고, bmi[cond]를 출력했다. 배열 형태의 자료에서는 두번째 요소를 출력하시오 같은 것 말고 조건을 넣은 변수도 출력이 되네요.

idx = np.where(bmi>24)
print(bmi[idx])
#라이브 코딩에서 사용하신 np.where는 배열에 요소를 검색해 인덱스로 반환한다.
#위에 바로 조건을 준 변수와 np.where 사용한 것 과의 차이는 차차 알아보겠습니다.


[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
[27.88755755 28.75558507 25.48723993 25.84368152]
[27.88755755 28.75558507 25.48723993 25.84368152]


In [79]:
# pandas 패키지 라이브러리를 불러오세요

import pandas as pd

# 아래 내용을 담는 pandas Dataframe 을 생성하세요
# {'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}

dict = {'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}

friend = pd.DataFrame(dict)
print(friend)

#dictionary는 트리구조의 검색 자료 구조. {}이런거 쓰는 자료는 dict이라고 한다.

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.


In [82]:
# 아래와 같은 dataframe을 만들어 보세요. (참고: 연도가 index가 되게 해 주세요)
"""
year dept     revenue
2015 Sales    30
2016 Sales    35
2017 Sales    40
"""

#DataFrame에서 특정 컬럼을 인덱스로 하는 경우 set_index 함수를 사용한다
import pandas as pd

data = {'year':[2015,2016,2017],
        'dept':['Sales','Sales','Sales'],
        'revenue': [30,35,40]}

df = pd.DataFrame(data)
df = df.set_index('year')
print(df)

# 2017년 데이터만 선택해 보세요
print(df.iloc[2])

#2017은 2번째 row에 위치해있다. 앞서 생성한 데이터프레임을 row값으로 잡으려고 iloc을 사용함. iloc[]하면 []안의 수에 해당하는 레코드 값들이 쭉 출력된다. 


# 조건(condition)을 활용하여 revenue 30 이상으로만 filter 해 보세요. reference: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/03_subset_data.html 
print(df[df["revenue"]>30])

#reference를 참조하였다. df라는 이름이 titanic일뿐 똑같은 에제가 나온다.




       dept  revenue
year                
2015  Sales       30
2016  Sales       35
2017  Sales       40
dept       Sales
revenue       40
Name: 2017, dtype: object
       dept  revenue
year                
2016  Sales       35
2017  Sales       40


In [91]:
# 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv' 자료를 불러와 dataframe으로 만들어 보세요 

import pandas as pd
df = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')

In [97]:
# 타이타닉 데이터의 shape은 어떻게 되나요? 
df.shape

# 타이타닉 row record에서 10~20번째 줄을 출력해 보세요
print(df[9:20])

# 타이타닉 데이터에서 'Survived', 'Age', 'Sex' 칼럼 데이터를 선택해 보세요
print(df[['Survived','Age','Sex']])

#데이터프레임의 라벨을 가지고 이 데이터를 column으로 찾아볼 수 있다,
#df에 []쓰고 해당 column값을 string으로 넣어준다. 
#*참고 : []-> Series [[]]->DataFrame

# 타이타닉 데이터에서 생존자 데이터만 골라보세요
survival = df['Survived'].isin([1])
print(df[survival])

# 생존자 데이터 중 여자, 남자 중 누가 더 많나요? 참고: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html
compare = df[survival]
print(compare.Sex.value_counts())



    Survived  Pclass  ... Parents/Children Aboard     Fare
9          1       2  ...                       0  30.0708
10         1       3  ...                       1  16.7000
11         1       1  ...                       0  26.5500
12         0       3  ...                       0   8.0500
13         0       3  ...                       5  31.2750
14         0       3  ...                       0   7.8542
15         1       2  ...                       0  16.0000
16         0       3  ...                       1  29.1250
17         1       2  ...                       0  13.0000
18         0       3  ...                       0  18.0000
19         1       3  ...                       0   7.2250

[11 rows x 8 columns]
     Survived   Age     Sex
0           0  22.0    male
1           1  38.0  female
2           1  26.0  female
3           1  35.0  female
4           0  35.0    male
..        ...   ...     ...
882         0  27.0    male
883         1  19.0  female
884         0   7