<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 2 / NOTE 2*

# 📝 Assignment

# $\chi^2$ 연습

원하는 데이터셋을 사용하여, categorical variable 간의 관계를 확인하세요:

- 상관관계가 있을 것 같은 쌍과 없을 것 같은 쌍 2가지에 대해서 해야합니다.

### 1) 데이터셋을 데이터프레임의 형태로 불러오세요.


In [52]:
# 코드를 작성하세요
import pandas as pd

titanic = pd.read_csv("https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv")
titanic = titanic.replace({'male': 1, 'female': 0})
titanic

Survived  Pclass  ... Parents/Children Aboard     Fare
0           0       3  ...                       0   7.2500
1           1       1  ...                       0  71.2833
2           1       3  ...                       0   7.9250
3           1       1  ...                       0  53.1000
4           0       3  ...                       0   8.0500
..        ...     ...  ...                     ...      ...
882         0       2  ...                       0  13.0000
883         1       1  ...                       0  30.0000
884         0       3  ...                       2  23.4500
885         1       1  ...                       0  30.0000
886         0       3  ...                       0   7.7500

[887 rows x 8 columns]

In [53]:
print(titanic[['Survived','Pclass','Siblings/Spouses Aboard','Age','Parents/Children Aboard', 'Sex']].dtypes)

Survived                     int64
Pclass                       int64
Siblings/Spouses Aboard      int64
Age                        float64
Parents/Children Aboard      int64
Sex                          int64
dtype: object


In [54]:
titanic_numcat = titanic[['Survived','Pclass','Siblings/Spouses Aboard','Age','Parents/Children Aboard', 'Sex']].astype('category')
print(titanic_numcat.dtypes)

Survived                   category
Pclass                     category
Siblings/Spouses Aboard    category
Age                        category
Parents/Children Aboard    category
Sex                        category
dtype: object


In [56]:
import numpy as np

observation_pclass_surv = pd.crosstab(titanic_numcat['Pclass'], titanic_numcat['Survived'])
print(observation_pclass_surv)
print('---')
observation_surv_pclass = pd.crosstab(titanic_numcat['Pclass'], titanic_numcat['Survived'])
print(observation_pclass_surv.sum())

Survived    0    1
Pclass            
1          80  136
2          97   87
3         368  119
---
Survived
0    545
1    342
dtype: int64


### 2) `stats.chi2_contingency()` 를 사용하여 $\chi^2$ test를 시행하세요:
 - 연관이 있는 변수 쌍에 대해서.
 - 연관이 없는 변수 쌍에 대해서.
 
상관관계가 있을 것 같은 변수 간의 검정 결과가 잘 설명 되나요?

#### 서로 연관이 있을것 같은 변수 쌍 (P class vs Survived)
  

In [57]:
from scipy.stats import chi2_contingency
chi2_contingency(observation_pclass_surv, correction = False)

(101.21674250560609,
 1.0496962042983216e-22,
 2,
 array([[132.71702368,  83.28297632],
        [113.05524239,  70.94475761],
        [299.22773393, 187.77226607]]))

```
우선, chi^2 test 값은 : 101.216
```
```
p value 는 0.00000000000000000000001049~ 라서. 거의 0과 같다.
chi^2의 H0 은 두 변수간 연관이 없다.
p-val is nearly 0, which means, we need to reject null and accept HA.
HA: 두 변수간 연관이 있다.
```
```
df = 2
(2-sample DF: (#of row -1)*(# of col -1) = 2 * 1 = 2)
```

#### 서로 연관이 없는 변수쌍 (Pclass vs Siblings and Spouses)

In [84]:
observation_pclass_sex = pd.crosstab(titanic_numcat['Pclass'], titanic_numcat['Sex'])
print(observation_pclass_sex)
print('---')
print(observation_pclass_sex.sum()) #sum by column

Sex       0    1
Pclass          
1        94  122
2        76  108
3       144  343
---
Sex
0    314
1    573
dtype: int64


In [85]:
chi2_contingency(observation_pclass_sex)

# chi^2 : (122+108+343)*(76+108)
# P value : 0.0002928685533212755 safe to say 0
# Degree of Freedom : 2 = (3-1)*(2-1)
# and shows array

(16.271573346171404,
 0.0002928685533212755,
 2,
 array([[ 76.46448703, 139.53551297],
        [ 65.13641488, 118.86358512],
        [172.39909808, 314.60090192]]))

```
chi^2 test value : 16.271573346171404
```
```
p-value : 0.0002928685533212755
H0 : 두 변수간 연관이 없다. HA : 두 변수간 연관이 있다.
P class 
```
```
df = 2
2-sample of df :(#of row -1)*(# of col -1) = (2-1) * (3-1) = 1 * 2 = 2
```


### 3) NumPy 를 사용하여 (Scipy를 사용하지 않고) $\chi^2$ test 시행

이 후 `chi2_contingency()`의 결과물과 비교해보세요

#### Original Sub

In [ ]:
# scipy.stats.chi2_contingency : "Chi-square test of independence of variables in a contingency table"
# scipy.stats.chisquare : "The chi square test tests the null hypothesis that the categorical data has the given frequencies."

In [36]:
# 관계 있음
import pandas as pd
import numpy as np

observation_pclass_surv = pd.crosstab(titanic_numcat['Pclass'], titanic_numcat['Survived'])
print(observation_pclass_surv)
print('---')
observation_surv_pclass = pd.crosstab(titanic_numcat['Pclass'], titanic_numcat['Survived'])
print(observation_pclass_surv.sum())

Survived    0    1
Pclass            
1          80  136
2          97   87
3         368  119
---
Survived
0    545
1    342
dtype: int64


In [67]:
# 코드를 작성하세요
obs_ps = np.array([80, 136, 97, 87, 368, 119]) #이렇게하면 안된다. Matrix 맞춰주어야 한다.
obs_ps

array([ 80, 136,  97,  87, 368, 119])

In [68]:
total_obs_ps = np.sum(obs_ps)
print(total_obs_ps)

# 컴퓨터가 봤을때는 같은 matrix라서 ㅇㅋ 하고 정상 작동했지만, 값이 달라졌다.
expected_ps = np.array([(80+97+368)*(80+136), (80+97+368)*(97+87), (80+97+368)*(368+119), (136+87+119)*(80+136), (136+87+119)*(97+87), (136+87+119)*(368+119)])

887


In [69]:
expected_ps = expected_ps / total_obs_ps
expected_ps # 위에서 chi2_contingency() 사용했을때의 array 와 같다.

#이것도 얼핏 보기에는, chi2_contingency와 숫자는 같아서 내가 맞는줄 알았다.

array([132.71702368, 113.05524239, 299.22773393,  83.28297632,
        70.94475761, 187.77226607])

In [70]:
sqrd = np.power(obs_ps - expected_ps, 2)
print(sqrd)

#이것도 나온 값은 같지만, matrix error.

[2.77908459e+03 5.26461902e+02 4.08960564e+04 1.38162650e+01
 8.82418170e+04 4.72962458e+03]


In [41]:
x2 = np.sum(sqrd / expected_ps)
print(x2)

#그래서 이런 해괴한 숫자가 나왔다.

1431.432854884952


In [45]:
from scipy.stats import chi2
print( 1 - chi2.cdf(x2, df = ((3-1)*(2-1))))

0.0


#### re-sub requested doing it again the 2 sample Chi-sq
와!!!~~WA 샌즈!!~~ Freakin, YES!!!!!!

In [76]:
# related
data = np.array([[80, 136],
                 [97, 87],
                 [368, 119]])

exp = np.array([
                [(80+97+368)*(80+136), (136+87+119)*(80+136)],
                [(80+97+368)*(97+87), (136+87+119)*(97+87)],
                [(80+97+368)*(368+119), (136+87+119)*(368+119)]
                ]) / np.sum(data)

chi = np.sum( np.power(data-exp,2)/exp )
print(chi) #와 대박사껀, 101.21674250 chi2_contingency() 와 동일한 값이 나왔다.
print( 1 - chi2.cdf(chi, df = (2-1)*(2-1) )) # 0.0 P value가 0에 가까운건 나도 아는 사실이다.

101.21674250560609
0.0


#### 왜 그동안 제대로 된 chi^2 값을 주지 않고 이상한 1431.432~~ 가 떴었나?

np.array() 에서 리스트?를 만들때, Matrix를 맞추지 않고 그냥 쭈욱 나열을 했었다. (그냥 그렇게 보여서...)
코드도 정상 작동을했었고 (이상한 값을 주기는 했지만) [에러는 발생하는데 에러코드는 뜨지않는 버그 encounter 2번째... 

구글링에서 (Either make those things matrices or...) 라는것을 보고.

진환님께서 올리신 Additional Contents에 있는것을 유심히 관찰하던 중,

내가 작성하던, np.array들이 matrix를 따르지 않는것을 발견하였다.

1. 오타 주의
2. array는 matrix를 맞춰서 잘 작성하자 (square bracket에 유의하자.)



In [ ]:
# 관계 없음
observation_pclass_sex = pd.crosstab(titanic_numcat['Pclass'], titanic_numcat['Sex'])
print(observation_pclass_sex)
print(observation_pclass_sex.sum())

Sex       0    1
Pclass          
1        94  122
2        76  108
3       144  343
Sex
0    314
1    573
dtype: int64


In [79]:
obs_pg = np.array([
                   [94, 122],
                   [76, 108],
                   [144, 343]
                   ]) # 아 그동안 진환님이 왜 이렇게 작성했는지 알겠다. []이거 차이점 최대한 덜 헷갈리게 보여주려고 그러셨었나보다.

In [80]:
total_obs_pg = np.sum(obs_pg)
print(total_obs_pg)

expected_pg = np.array([
                        [(94+76+144)*(94+122), (122+108+343)*(94+122)],
                        [(94+76+144)*(76+108), (122+108+343)*(76+108)],
                        [(94+76+144)*(144+343), (122+108+343)*(144+343)]
                        ])

887


In [81]:
expected_pg = expected_pg / total_obs_pg
expected_pg #ㅗㅜㅑ 이제 matrices 맞춰서 나온다. ㅎㅎ

array([[ 76.46448703, 139.53551297],
       [ 65.13641488, 118.86358512],
       [172.39909808, 314.60090192]])

In [82]:
sqrd_pg = np.power(obs_pg - expected_pg, 2)
print(sqrd_pg)

[[307.49421495 307.49421495]
 [118.01748162 118.01748162]
 [806.50877195 806.50877195]]


In [83]:
x2_pg = np.sum(sqrd_pg / expected_pg)
print(x2_pg)

#아 드디어!!! 올바른 답이 나온다!!!

16.271573346171404


## 도전 과제:

### 1. 작성된 코드들을 함수의 형태로 변경하여, 읽거나 재 사용 하기 쉽게 리팩토링 해보세요.



### 2. 다음 주제들에 대해서, 공부 후 간단한 설명글을 작성해보세요:

1. 통계에서 표본 "추정"이란 무엇일까요?
(What is "estimation" in statistics?)
>

2. 가설검정이란 무엇일까요? 그것이 어떻게 쓰이나요?  (What is a Hypothesis Test and where it's used?) **(Type I and Type II Error...)**
> 한국에서 팔리는 자동차중, 50%는 외제차일것이다! 라는, 가설을 세웠을때
그 가설이 맞는지, 통계학적으로 test 하는것을 Hypothesis Testing 이라고 한다.
> 전체를 검증하기는 어렵기 때문에, 표본(sample)을 검증해야 하는데, 그 것이 맞나 확인하는 것

3. "귀무가설"이란 무엇인가요? (What is a Null Hypothesis?) 
> 귀 : 돌아갈 귀, [1. 돌아가다, 돌아오다 2. 돌려보내다 3. 따르다, 붙좇다(존경하거나 섬겨 따르다) 4. (몸을)의탁하다]
무: 없을 무
>>H0 is the commonly accepted fact.
흔히/보통 일반적으로 받아드려지는 사실.


4. p-value와 그것이 의미하는 바는 무엇인가요? (What is a P-value and what does it mean?)
> p value는 H0을 뒷받침 해주는/ 근거로 사용 하는 값.
>> If the P-value is less than (or equal to) significance lvl : (alpha) or (1 - confidence lvl), reject the null hypothesis in favor of the alternative hypothesis. 
If the P-value is greater than, do not reject the null hypothesis.

> p value가 크면 클수록, H0일 확률이 크다! 우리가 정한 significance lvl 이하 일때는, reject H0
> 우리가 scipy로 볼 수 있는 P-value는
> H0가 똑같이 발현될 확률! 이라고 생각하면 좋을듯 하다...
> P value가 낮으면 낮을 수 록 H0가 발혈될 확률이 낮아 지기때문에 H0를 reject 한다.

5. "통계적으로 유의하다" 에 대해서 설명해보세요 (Explain "statistical significant")
> “Statistical significance helps quantify whether a result is likely due to chance or to some factor of interest,”
> statistical significance 는 결과가 단순히 우연히 일어난것인지 아닌지 판단하는데 도움을 주는 값
> 일반적으로 우리가 봤을땐, 우연히 들어 맞은것이 처럼 보였어도, 통계적 측면에서 보았을때, 큰 의미!


6. 테스트 통계치 (test statistic) 가 무엇인지, 그리고 p-value와 어떻게 연관이 있나요? (What is test statistic and how is it related to p value)
> 

7. 자유도 ("degrees of freedom")란 그리고 다음 경우에 대해서 어떻게 계산을 하나요?
(How do you find df when) 1-sammple, 2-sample $\chi^2$ test
>
