<a href="https://colab.research.google.com/github/bang997/ds-admission-challenge/blob/master/%EC%96%B4%EB%93%9C%EB%AF%B8%EC%85%98_%EC%B1%8C%EB%A6%B0%EC%A7%80_%EA%B3%BC%EC%A0%9C_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge

- 코드스테이츠 DS 부트캠프 어드미션을 위한 Challenge 과제 입니다. 
- 아래 challenge 를 풀기 위해 제공된 강의가 모든 것을 알려주진 않습니다. 
- 따라서 필요한 부분은 스스로 google 검색을 통해 이 challenge 를 완성해 주셔야 합니다. 
- 각 shell 에 필요한 부분을 작성하신 후 함께 링크를 제출해 주시면 됩니다.
- 모든 결과물은 하나의 shell에서 모두 실행될 수 있도록 print문을 사용해 주세요. run all 했을 때 전체 shell 이 모두 잘 실행될 수 있도록 관리해 주세요.



In [279]:
# 1. 다음의 list 에서 두 번째 list elemnet 를 print 해 보세요
list_01 = ['Paul', 'John', 'Ringo', 'George']

print(list_01[1])

John


In [280]:
# 2. 다음의 list in the list에서 두 번째 element 를 print 해 보세요
list_02 = [['Paul', 'John', 'Ringo', 'George'], ['a', 'b', 'c', 'd'], [1,2,3,4]]

print(list_02[0][1]) #john
print(list_02[1][2]) #c
print(list_02[2][1]) #2

John
c
2


In [281]:
# Initializing list  
list_01 = [ 1, 6, 3, 5, 3, 4 ] 
list_02 = [ 1, 6, 3, 5, 3 ] 
 
# for loop을 이용하여 두 개의 리스트 안에 4가 있는지 없는지 print 하는 코드를 작성하세요
for i in list_01:
  if 4 in list_01:
    print("exist")
    break
  else:
    print("not exist")
    break

for i in list_02:
  if 4 in list_02:
    print("exist")
    break
  else:
    print("not exist")
    break

exist
not exist


In [295]:
# 위 코드 역할을 하는 함수를 작성해 보세요
def check_value(element, l):
  if l.count(element)>0:
    print("exist")
  else:
    print("not exist")
  return

check_value(4, list_01)
check_value(4, list_02)

print("---")

def value_exist(l):
  count=0
  for i in l:
    if i == 4: 
      count = 1
  if count == 1: 
    print("exist")
  else: 
    print("not exist")
  return

value_exist(list_01)
value_exist(list_02)

exist
not exist
---
exist
not exist


In [303]:
#추가문제
## for loop를 이용하여 1부터 100까지의 숫자 중 홀수의 총합을 구하시오.
result_1 = 0
for i in range(1,101):
  if i % 2 == 1:
    result_1 += i
print(result_1)

print('--')

## for loop를 이용하여 1부터 100까지의 숫자 중 짝수의 총합을 구하시오.
result_2 = 0
for i in range(1,101):
  if i % 2 == 0:
    result_2 += i
print(result_2)

print('--')

## 1부터 100까지의 총합
sum(range(1,101))

2500
--
2550
--


5050

In [305]:
#변형문제
# 각 리스트 안에 4가 몇 개 있는지 개수를 세보시오.
list_04 = [ 1, 6, 3, 5, 3, 4, 4, 4] 
list_05 = [ 1, 6, 3, 5, 4 ] 
 
count=0
for i in list_04:
  if i == 4:
    count += 1
print("list_04 :",count,"개")

print('--')

count=0
for i in list_05:
  if i == 4:
    count += 1
print("list_05 :",count,'개')

list_04 : 3 개
--
list_05 : 1 개


In [284]:
#추가문제
# 위 코드 역할을 하는 함수를 작성해 보세요
def my_condition(x):
  return x == 4

print(sum(1 for x in list_04 if my_condition(x)),'개')
print('--')
print(sum(1 for x in list_05 if my_condition(x)),'개')

3 개
--
1 개


In [285]:
list_03 = [4, 5, 8, 9, 10] 

# 위 list element 중 8보다 큰 숫자가 몇 개가 있는지 코드로 작성해 보세요. 

##count=0
count=0
for i in list_03:
  if i > 8:
    count += 1
print(count,"개")

print('--')

##함수 이용
def more_than_8(y):
  return y > 8

print(sum(1 for y in list_03 if more_than_8(y)), '개')

2 개
--
2 개


In [286]:
#추가문제
# data ** 2
data = [0,1,2,3,4,5,6,7,8,9]

## for loop
answer = []
for i in data:
  answer.append(i ** 2)
print(answer)

## numpy array
import numpy as np
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(ar ** 2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [287]:
#추가문제
# NumPy로 아래와 같은 행렬 구성해보기
'''
 10 20 30 40
 50 60 70 80
'''

import numpy as np
sample_data = np.array([[10,20,30,40],
                        [50,60,70,80]])
print(sample_data)

[[10 20 30 40]
 [50 60 70 80]]


In [288]:
# BMI
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# bmi = weight / height ** 2 를 numpy array 활용하여 구해보세요
import numpy as np
h = np.array(height)
w = np.array(weight)

print(w/h ** 2)

# bmi 가 24 이상인 값들만 선택해 보세요
bmi = w / h ** 2
idx = np.where(bmi>24)

print(bmi[idx])

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
[27.88755755 28.75558507 25.48723993 25.84368152]


In [289]:
# Numpy where 예제
## 리스트 안에서 10보다 큰 숫자를 찾아 0으로 치환하시오.

import numpy as np

a = np.array([1,2,3,10,20,30,0.1,0.2])

#[In]np.where(a)  ##인덱스 출력
#[out]array([0, 1, 2, 3, 4, 5, 6, 7])
 

print(np.where(a>10, 0, a))

[ 1.   2.   3.  10.   0.   0.   0.1  0.2]


In [290]:
# pandas 패키지 라이브러리를 불러오세요
import pandas as pd

# 아래 내용을 담는 pandas Dataframe 을 생성하세요
# {'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']}
data = {
        'Bob': ['I liked it.', 'It was awful.'],
        'Sue': ['Pretty good.', 'Bland.']
        }

pd.DataFrame(data, index = ['A', 'B'])

Bob           Sue
A    I liked it.  Pretty good.
B  It was awful.        Bland.

In [291]:
# 아래와 같은 dataframe을 만들어 보세요. (참고: 연도가 index가 되게 해 주세요)
"""
year dept     revenue   cost    profit    ranking
2015 Sales      30       15       15         2
2016 Sales      35       25       10         3
2017 Sales      40       10       30         1
"""

data = {'dept' : 'sales', 'revenue' : [30, 35, 40]}

year = [2015, 2016, 2017]
DF =pd.DataFrame(data, index=year)
print(DF)
print("--")
# 2017년 데이터만 선택해 보세요
print(DF.iloc[2])
print("--")
# 조건(condition)을 활용하여 revenue 30 이상으로만 filter 해 보세요. reference: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/03_subset_data.html 
DF[DF['revenue'] >= 30]

       dept  revenue
2015  sales       30
2016  sales       35
2017  sales       40
--
dept       sales
revenue       40
Name: 2017, dtype: object
--


dept  revenue
2015  sales       30
2016  sales       35
2017  sales       40

In [292]:
# 변형문제
# 아래와 같은 dataframe을 만들어 보세요. (참고: 연도가 index가 되게 해 주세요)
"""
year dept     revenue   cost    profit    ranking
2015 Sales      30       15       15         2
2016 Sales      35       25       10         3
2017 Sales      40       10       30         1
"""
## index = year
data = {
    'dept' : 'Sales', 
    'revenue' : [30,35,40], 
    'cost' : [15,25,10], 
    'profit' : [15,10,30], 
    'ranking' : [2,3,1]
      }

year = [2015,2016,2017]
df_sample = pd.DataFrame(data, index = year)
print(df_sample)
print("--")

## set_index
df_sample1=pd.DataFrame(
    {'year' : [2015,2016,2017],
     'dept' : 'Sales', 
     'revenue' : [30,35,40], 
     'cost' : [15,25,10], 
     'profit' : [15,10,30], 
     'ranking' : [2,3,1]}
    )
df_sample1=df_sample1.set_index('year')
print(df_sample1)
print("--")

# 2016,2017년 데이터만 선택해 보세요
print(df_sample.loc[2016])
print(df_sample.iloc[2])
print("--")

# 조건(condition)을 활용하여 revenue 30 이상 & profit 15 이상으로 filter 해 보세요. reference: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/03_subset_data.html 
df_rev = df_sample['revenue'] >= 30
df_pro = df_sample['profit'] >= 15
subset_df = df_sample[df_rev & df_pro]
subset_df

       dept  revenue  cost  profit  ranking
2015  Sales       30    15      15        2
2016  Sales       35    25      10        3
2017  Sales       40    10      30        1
--
       dept  revenue  cost  profit  ranking
year                                       
2015  Sales       30    15      15        2
2016  Sales       35    25      10        3
2017  Sales       40    10      30        1
--
dept       Sales
revenue       35
cost          25
profit        10
ranking        3
Name: 2016, dtype: object
dept       Sales
revenue       40
cost          10
profit        30
ranking        1
Name: 2017, dtype: object
--


dept  revenue  cost  profit  ranking
2015  Sales       30    15      15        2
2017  Sales       40    10      30        1

In [293]:
# 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv' 자료를 불러와 dataframe으로 만들어 보세요 
df=pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')
print(df.head())
print(df.tail())

   Survived  Pclass  ... Parents/Children Aboard     Fare
0         0       3  ...                       0   7.2500
1         1       1  ...                       0  71.2833
2         1       3  ...                       0   7.9250
3         1       1  ...                       0  53.1000
4         0       3  ...                       0   8.0500

[5 rows x 8 columns]
     Survived  Pclass  ... Parents/Children Aboard   Fare
882         0       2  ...                       0  13.00
883         1       1  ...                       0  30.00
884         0       3  ...                       2  23.45
885         1       1  ...                       0  30.00
886         0       3  ...                       0   7.75

[5 rows x 8 columns]


In [294]:
# 타이타닉 데이터의 shape은 어떻게 되나요? 
print(df.shape)
print("--")
# 타이타닉 row record에서 10~20번째 줄을 출력해 보세요
print(df.iloc[9:20])
print('--')
# 타이타닉 데이터에서 'Survived', 'Age', 'Sex' 칼럼 데이터를 선택해 보세요
print(df[['Survived', 'Age', 'Sex']])
print('--')
# 타이타닉 데이터에서 생존자 데이터만 골라보세요
print(df[df["Survived"] == 1])
print('--')
# 생존자 데이터 중 여자, 남자 중 누가 더 많나요? 참고: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html
alive_01 = df['Survived'] == 1
alive_02 = df['Sex'] == 'male'
alive_03 = df['Sex'] == 'female'

alive_M = df[alive_01 & alive_02].shape[0]
alive_F = df[alive_01 & alive_03].shape[0]

if alive_M > alive_F:
  print('생존자 중엔 남자가 많습니다.')
elif alive_M == alive_F:
  print('남자와 여자의 생존자 수가 일치합니다.')
else:
  print('생존자 중엔 여자가 많습니다.')

(887, 8)
--
Series([], Name: revenue, dtype: bool)
--
     Survived   Age     Sex
0           0  22.0    male
1           1  38.0  female
2           1  26.0  female
3           1  35.0  female
4           0  35.0    male
..        ...   ...     ...
882         0  27.0    male
883         1  19.0  female
884         0   7.0  female
885         1  26.0    male
886         0  32.0    male

[887 rows x 3 columns]
--
     Survived  Pclass  ... Parents/Children Aboard     Fare
1           1       1  ...                       0  71.2833
2           1       3  ...                       0   7.9250
3           1       1  ...                       0  53.1000
8           1       3  ...                       2  11.1333
9           1       2  ...                       0  30.0708
..        ...     ...  ...                     ...      ...
871         1       3  ...                       0   7.2250
875         1       1  ...                       1  83.1583
876         1       2  ...                 